name: Diff CCD definition

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

  buildBranch:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v3
        with:
          path: branch
          repository: hmcts/nfdiv-case-api # TODO remove
          ref: nfdiv-date-picker # TODO remove
      - name: Build
        run: ./branch/.gradlew generateCCDConfig
      - name: Set JSON path
        run: echo "::set-output name=path::build/branch/definitions/NFD"

  buildMaster:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          path: master
          repository: hmcts/nfdiv-case-api # TODO remove
      - name: Build
        run: ./master/.gradlew generateCCDConfig
      - name: Set JSON path
        run: echo "::set-output name=path::build/master/definitions/NFD"

  report:
    runs-on: ubuntu-latest
    needs: [buildBranch, buildMaster]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Generate report
        run: |
          echo "::set-output name=content::$(npm start ${{jobs.buildMaster.outputs.path}} ${{jobs.buildBranch.outputs.path}})')"
        id: report
      - name: Add report
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: 'CCD diff'
          comment_includes: 'CCD diff ${{steps.report.content}}'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
